//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.16.0
//     from Assets/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputController.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputController: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""af9450ba-218f-4f79-a3d6-827cbaa3990d"",
            ""actions"": [
                {
                    ""name"": ""Fireball"",
                    ""type"": ""Button"",
                    ""id"": ""65cbda46-3c59-45c5-84c0-f4670e81305b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropEgg"",
                    ""type"": ""Button"",
                    ""id"": ""c8406085-9a15-49ea-abe0-cfeaa5057678"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""9df870a7-2b9e-4307-b0ce-553eb6ecbcc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""03838bde-c4e5-4a85-b37a-f61f8f371e17"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpRight"",
                    ""type"": ""Button"",
                    ""id"": ""711ca112-25f4-4f11-9efe-0c329e2f5064"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpLeft"",
                    ""type"": ""Button"",
                    ""id"": ""9b324f8c-5dcd-463d-927a-6b176a5951c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpHold"",
                    ""type"": ""Button"",
                    ""id"": ""7a1b2628-cdb6-44df-96c2-b30778de634d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPress"",
                    ""type"": ""Button"",
                    ""id"": ""c8666c9d-9f9a-44c8-bb01-83f974e4900a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""2f75b153-ec9f-4888-b592-e5c396cc1467"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Parachute"",
                    ""type"": ""Button"",
                    ""id"": ""267adbde-d536-4f69-acf1-6296c8214c71"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6a7bb245-7739-4352-a7ae-757bdda03107"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashSlash"",
                    ""type"": ""Button"",
                    ""id"": ""1cbbf4c4-de14-4525-b189-264d8197cd0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.32)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EggJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""35f59893-3e75-40e2-a4d0-0dee34bd09a0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchAmmoRight"",
                    ""type"": ""Button"",
                    ""id"": ""c40449bd-286c-47ed-a608-ea7c16437bc2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parry"",
                    ""type"": ""Button"",
                    ""id"": ""39317f21-516d-4ac9-9092-65462f989d96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finger1"",
                    ""type"": ""Value"",
                    ""id"": ""f3dba7fd-62b8-4eca-8fb3-d7282a84aded"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Finger2"",
                    ""type"": ""Value"",
                    ""id"": ""bdb83564-aa55-43f1-9528-78b208745e8a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cursor"",
                    ""type"": ""Value"",
                    ""id"": ""e16de448-4c6f-47e7-a3c8-eff0103230a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""b5a7659e-a41d-4218-b2c1-a8c67c25fb4c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finger1Press"",
                    ""type"": ""Button"",
                    ""id"": ""402a2127-185b-4a1f-941e-4c8d51739f64"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Finger2Press"",
                    ""type"": ""Button"",
                    ""id"": ""52ec2e1e-f0d9-4a07-954c-509764b986e5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScytheStick"",
                    ""type"": ""Value"",
                    ""id"": ""f467a2e1-3b7a-4f5e-82ec-910d70491803"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""cdd2efe0-b639-40b2-9f91-354981990b5f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1509b281-cd61-4491-b3f1-45db31dbb1e8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""JumpHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""355bd070-138f-4545-96cf-bdcafae4e0e9"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""JumpHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b7079e5-c39a-4c93-9bc7-410e1ac8487c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""JumpLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd76ad71-f0a6-4336-9bd4-73384afa7ea9"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""JumpLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c57ff5b-84f5-48d5-a121-b44e03cce482"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""JumpRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b08dbd0-a67f-40f2-bffa-22366bd91f60"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""JumpRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8f9e6a0-1c12-40f2-ab4c-42dfceff0d90"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6985edf9-1ce9-497d-a597-f45b7275fa2c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1118d868-368b-43b5-88e6-4caae8c07017"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9749ddd7-ac4f-4761-8675-9edfef8728e1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5ef087a-7730-41b6-b474-5933a45b45f7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DropEgg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b7f91a3-6adb-4672-8351-0d8d5e2a09f4"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""DropEgg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1d3526f-f1c8-41dd-9c85-ad65b57ce2bb"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Fireball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60037d80-6c76-40cd-b93a-47e30005c252"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Fireball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf6de740-0bd6-4f1d-abb7-6d15f43f259f"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70d7505d-0113-4039-8d8f-7839975a94fc"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d3349ca-646a-426f-a376-dbb4c1bd7a64"",
                    ""path"": ""<Keyboard>/#(C)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Parachute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02baf8d2-731d-48a2-9e7c-d6fdb850d492"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Parachute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71785b00-5b5a-4d60-a60a-bfe45c783bc6"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47e0b5fe-6038-46bf-aba8-7552f7a46f65"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6624c8c8-2105-4363-885c-22ba6cf97fdf"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DashSlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7a56b1f-185b-4242-b3b9-7cee360a64d4"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""DashSlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f4be38a-3bd6-42be-b8dd-b1d9cd33a48c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""EggJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f47d7a75-c16b-4703-b2e2-e8a745cb011e"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SwitchAmmoRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c4195f9-5d8c-484e-81f1-28d1fd5e785e"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard;Mobile"",
                    ""action"": ""SwitchAmmoRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf7b388c-28cc-4057-87aa-fadfcf6c81c8"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""038266cd-44a2-4c9b-b5cc-54d43586cd4d"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b80bf30-2322-4d9e-9f05-7b81dfc016b8"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff58ee2f-19e1-4384-8bbb-aca16047ab20"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8441d966-0d2f-4f44-a9e2-c0fa72351951"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdff57cc-ec27-401a-896c-02da72ebe67c"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Finger1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de286ed4-8cb4-49cf-8134-d6ccff632993"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Finger2Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eb466c8-22a1-4b84-a9d1-a0544dc66093"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""ScytheStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebccc469-00fb-4065-80b7-c0f616635379"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard;Mobile"",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LevelCreator"",
            ""id"": ""89737611-948f-48ca-9565-39ddf240200a"",
            ""actions"": [
                {
                    ""name"": ""Finger1Press"",
                    ""type"": ""Button"",
                    ""id"": ""45e70696-90c1-48b5-9e35-5123eba41f05"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finger1Pos"",
                    ""type"": ""Value"",
                    ""id"": ""8f0d85d4-eca9-4570-acd9-098497705e1e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CursorClick"",
                    ""type"": ""Button"",
                    ""id"": ""d307f141-d5c9-40b2-84f1-4db248acddb1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorPos"",
                    ""type"": ""Value"",
                    ""id"": ""77f05261-ace6-490b-bf5b-dd444dc2cb1e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Finger2Press"",
                    ""type"": ""Button"",
                    ""id"": ""9bee5ed2-7d43-4772-afa3-ace18b21e814"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finger2Pos"",
                    ""type"": ""Value"",
                    ""id"": ""0ff857c1-399a-4105-ad47-04d10af53a7f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ShiftClick"",
                    ""type"": ""Button"",
                    ""id"": ""78625192-8d1f-40c6-b46b-31e4aa44c5b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a7f57d9c-a9ab-413e-b4a9-b17c28c501cc"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b4f6e57-bff5-4d00-8090-ae98b2a41019"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger1Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3607148-b743-4ea9-a632-7173f5db09d5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""CursorClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bee76cf7-05e0-4c1a-9504-af667fc8b6ed"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""CursorPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec2aa473-0e1b-4028-bee4-a8d0dcc93ae9"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger2Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30cbee94-bf1f-471c-be35-763e1702ad0d"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger2Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc1688c4-01b0-46a0-a08f-63824f8f3159"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""ShiftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GamepadCursor"",
            ""id"": ""3f801783-8d0a-455d-a220-7bd0355104c1"",
            ""actions"": [
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""ce542715-01ed-4248-9314-75738a6ebd53"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""8b2a06f1-1f50-453c-8998-297366de19c3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e2e454a4-53cf-4140-957e-e3de14336bf3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": "";Keyboard;Mobile"",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b05097a7-15d4-4e82-b158-9249b0eab997"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard;Mobile"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Mobile"",
            ""bindingGroup"": ""Mobile"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_Fireball = m_Movement.FindAction("Fireball", throwIfNotFound: true);
        m_Movement_DropEgg = m_Movement.FindAction("DropEgg", throwIfNotFound: true);
        m_Movement_Dash = m_Movement.FindAction("Dash", throwIfNotFound: true);
        m_Movement_Drop = m_Movement.FindAction("Drop", throwIfNotFound: true);
        m_Movement_JumpRight = m_Movement.FindAction("JumpRight", throwIfNotFound: true);
        m_Movement_JumpLeft = m_Movement.FindAction("JumpLeft", throwIfNotFound: true);
        m_Movement_JumpHold = m_Movement.FindAction("JumpHold", throwIfNotFound: true);
        m_Movement_TouchPress = m_Movement.FindAction("TouchPress", throwIfNotFound: true);
        m_Movement_TouchPosition = m_Movement.FindAction("TouchPosition", throwIfNotFound: true);
        m_Movement_Parachute = m_Movement.FindAction("Parachute", throwIfNotFound: true);
        m_Movement_Jump = m_Movement.FindAction("Jump", throwIfNotFound: true);
        m_Movement_DashSlash = m_Movement.FindAction("DashSlash", throwIfNotFound: true);
        m_Movement_EggJoystick = m_Movement.FindAction("EggJoystick", throwIfNotFound: true);
        m_Movement_SwitchAmmoRight = m_Movement.FindAction("SwitchAmmoRight", throwIfNotFound: true);
        m_Movement_Parry = m_Movement.FindAction("Parry", throwIfNotFound: true);
        m_Movement_Finger1 = m_Movement.FindAction("Finger1", throwIfNotFound: true);
        m_Movement_Finger2 = m_Movement.FindAction("Finger2", throwIfNotFound: true);
        m_Movement_Cursor = m_Movement.FindAction("Cursor", throwIfNotFound: true);
        m_Movement_MouseClick = m_Movement.FindAction("MouseClick", throwIfNotFound: true);
        m_Movement_Finger1Press = m_Movement.FindAction("Finger1Press", throwIfNotFound: true);
        m_Movement_Finger2Press = m_Movement.FindAction("Finger2Press", throwIfNotFound: true);
        m_Movement_ScytheStick = m_Movement.FindAction("ScytheStick", throwIfNotFound: true);
        m_Movement_Trigger = m_Movement.FindAction("Trigger", throwIfNotFound: true);
        // LevelCreator
        m_LevelCreator = asset.FindActionMap("LevelCreator", throwIfNotFound: true);
        m_LevelCreator_Finger1Press = m_LevelCreator.FindAction("Finger1Press", throwIfNotFound: true);
        m_LevelCreator_Finger1Pos = m_LevelCreator.FindAction("Finger1Pos", throwIfNotFound: true);
        m_LevelCreator_CursorClick = m_LevelCreator.FindAction("CursorClick", throwIfNotFound: true);
        m_LevelCreator_CursorPos = m_LevelCreator.FindAction("CursorPos", throwIfNotFound: true);
        m_LevelCreator_Finger2Press = m_LevelCreator.FindAction("Finger2Press", throwIfNotFound: true);
        m_LevelCreator_Finger2Pos = m_LevelCreator.FindAction("Finger2Pos", throwIfNotFound: true);
        m_LevelCreator_ShiftClick = m_LevelCreator.FindAction("ShiftClick", throwIfNotFound: true);
        // GamepadCursor
        m_GamepadCursor = asset.FindActionMap("GamepadCursor", throwIfNotFound: true);
        m_GamepadCursor_MoveCursor = m_GamepadCursor.FindAction("MoveCursor", throwIfNotFound: true);
        m_GamepadCursor_Select = m_GamepadCursor.FindAction("Select", throwIfNotFound: true);
    }

    ~@InputController()
    {
        UnityEngine.Debug.Assert(!m_Movement.enabled, "This will cause a leak and performance issues, InputController.Movement.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_LevelCreator.enabled, "This will cause a leak and performance issues, InputController.LevelCreator.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_GamepadCursor.enabled, "This will cause a leak and performance issues, InputController.GamepadCursor.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private List<IMovementActions> m_MovementActionsCallbackInterfaces = new List<IMovementActions>();
    private readonly InputAction m_Movement_Fireball;
    private readonly InputAction m_Movement_DropEgg;
    private readonly InputAction m_Movement_Dash;
    private readonly InputAction m_Movement_Drop;
    private readonly InputAction m_Movement_JumpRight;
    private readonly InputAction m_Movement_JumpLeft;
    private readonly InputAction m_Movement_JumpHold;
    private readonly InputAction m_Movement_TouchPress;
    private readonly InputAction m_Movement_TouchPosition;
    private readonly InputAction m_Movement_Parachute;
    private readonly InputAction m_Movement_Jump;
    private readonly InputAction m_Movement_DashSlash;
    private readonly InputAction m_Movement_EggJoystick;
    private readonly InputAction m_Movement_SwitchAmmoRight;
    private readonly InputAction m_Movement_Parry;
    private readonly InputAction m_Movement_Finger1;
    private readonly InputAction m_Movement_Finger2;
    private readonly InputAction m_Movement_Cursor;
    private readonly InputAction m_Movement_MouseClick;
    private readonly InputAction m_Movement_Finger1Press;
    private readonly InputAction m_Movement_Finger2Press;
    private readonly InputAction m_Movement_ScytheStick;
    private readonly InputAction m_Movement_Trigger;
    /// <summary>
    /// Provides access to input actions defined in input action map "Movement".
    /// </summary>
    public struct MovementActions
    {
        private @InputController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MovementActions(@InputController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Movement/Fireball".
        /// </summary>
        public InputAction @Fireball => m_Wrapper.m_Movement_Fireball;
        /// <summary>
        /// Provides access to the underlying input action "Movement/DropEgg".
        /// </summary>
        public InputAction @DropEgg => m_Wrapper.m_Movement_DropEgg;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Dash".
        /// </summary>
        public InputAction @Dash => m_Wrapper.m_Movement_Dash;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Drop".
        /// </summary>
        public InputAction @Drop => m_Wrapper.m_Movement_Drop;
        /// <summary>
        /// Provides access to the underlying input action "Movement/JumpRight".
        /// </summary>
        public InputAction @JumpRight => m_Wrapper.m_Movement_JumpRight;
        /// <summary>
        /// Provides access to the underlying input action "Movement/JumpLeft".
        /// </summary>
        public InputAction @JumpLeft => m_Wrapper.m_Movement_JumpLeft;
        /// <summary>
        /// Provides access to the underlying input action "Movement/JumpHold".
        /// </summary>
        public InputAction @JumpHold => m_Wrapper.m_Movement_JumpHold;
        /// <summary>
        /// Provides access to the underlying input action "Movement/TouchPress".
        /// </summary>
        public InputAction @TouchPress => m_Wrapper.m_Movement_TouchPress;
        /// <summary>
        /// Provides access to the underlying input action "Movement/TouchPosition".
        /// </summary>
        public InputAction @TouchPosition => m_Wrapper.m_Movement_TouchPosition;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Parachute".
        /// </summary>
        public InputAction @Parachute => m_Wrapper.m_Movement_Parachute;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_Movement_Jump;
        /// <summary>
        /// Provides access to the underlying input action "Movement/DashSlash".
        /// </summary>
        public InputAction @DashSlash => m_Wrapper.m_Movement_DashSlash;
        /// <summary>
        /// Provides access to the underlying input action "Movement/EggJoystick".
        /// </summary>
        public InputAction @EggJoystick => m_Wrapper.m_Movement_EggJoystick;
        /// <summary>
        /// Provides access to the underlying input action "Movement/SwitchAmmoRight".
        /// </summary>
        public InputAction @SwitchAmmoRight => m_Wrapper.m_Movement_SwitchAmmoRight;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Parry".
        /// </summary>
        public InputAction @Parry => m_Wrapper.m_Movement_Parry;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Finger1".
        /// </summary>
        public InputAction @Finger1 => m_Wrapper.m_Movement_Finger1;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Finger2".
        /// </summary>
        public InputAction @Finger2 => m_Wrapper.m_Movement_Finger2;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Cursor".
        /// </summary>
        public InputAction @Cursor => m_Wrapper.m_Movement_Cursor;
        /// <summary>
        /// Provides access to the underlying input action "Movement/MouseClick".
        /// </summary>
        public InputAction @MouseClick => m_Wrapper.m_Movement_MouseClick;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Finger1Press".
        /// </summary>
        public InputAction @Finger1Press => m_Wrapper.m_Movement_Finger1Press;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Finger2Press".
        /// </summary>
        public InputAction @Finger2Press => m_Wrapper.m_Movement_Finger2Press;
        /// <summary>
        /// Provides access to the underlying input action "Movement/ScytheStick".
        /// </summary>
        public InputAction @ScytheStick => m_Wrapper.m_Movement_ScytheStick;
        /// <summary>
        /// Provides access to the underlying input action "Movement/Trigger".
        /// </summary>
        public InputAction @Trigger => m_Wrapper.m_Movement_Trigger;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MovementActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MovementActions" />
        public void AddCallbacks(IMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementActionsCallbackInterfaces.Add(instance);
            @Fireball.started += instance.OnFireball;
            @Fireball.performed += instance.OnFireball;
            @Fireball.canceled += instance.OnFireball;
            @DropEgg.started += instance.OnDropEgg;
            @DropEgg.performed += instance.OnDropEgg;
            @DropEgg.canceled += instance.OnDropEgg;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Drop.started += instance.OnDrop;
            @Drop.performed += instance.OnDrop;
            @Drop.canceled += instance.OnDrop;
            @JumpRight.started += instance.OnJumpRight;
            @JumpRight.performed += instance.OnJumpRight;
            @JumpRight.canceled += instance.OnJumpRight;
            @JumpLeft.started += instance.OnJumpLeft;
            @JumpLeft.performed += instance.OnJumpLeft;
            @JumpLeft.canceled += instance.OnJumpLeft;
            @JumpHold.started += instance.OnJumpHold;
            @JumpHold.performed += instance.OnJumpHold;
            @JumpHold.canceled += instance.OnJumpHold;
            @TouchPress.started += instance.OnTouchPress;
            @TouchPress.performed += instance.OnTouchPress;
            @TouchPress.canceled += instance.OnTouchPress;
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
            @Parachute.started += instance.OnParachute;
            @Parachute.performed += instance.OnParachute;
            @Parachute.canceled += instance.OnParachute;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @DashSlash.started += instance.OnDashSlash;
            @DashSlash.performed += instance.OnDashSlash;
            @DashSlash.canceled += instance.OnDashSlash;
            @EggJoystick.started += instance.OnEggJoystick;
            @EggJoystick.performed += instance.OnEggJoystick;
            @EggJoystick.canceled += instance.OnEggJoystick;
            @SwitchAmmoRight.started += instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.performed += instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.canceled += instance.OnSwitchAmmoRight;
            @Parry.started += instance.OnParry;
            @Parry.performed += instance.OnParry;
            @Parry.canceled += instance.OnParry;
            @Finger1.started += instance.OnFinger1;
            @Finger1.performed += instance.OnFinger1;
            @Finger1.canceled += instance.OnFinger1;
            @Finger2.started += instance.OnFinger2;
            @Finger2.performed += instance.OnFinger2;
            @Finger2.canceled += instance.OnFinger2;
            @Cursor.started += instance.OnCursor;
            @Cursor.performed += instance.OnCursor;
            @Cursor.canceled += instance.OnCursor;
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
            @Finger1Press.started += instance.OnFinger1Press;
            @Finger1Press.performed += instance.OnFinger1Press;
            @Finger1Press.canceled += instance.OnFinger1Press;
            @Finger2Press.started += instance.OnFinger2Press;
            @Finger2Press.performed += instance.OnFinger2Press;
            @Finger2Press.canceled += instance.OnFinger2Press;
            @ScytheStick.started += instance.OnScytheStick;
            @ScytheStick.performed += instance.OnScytheStick;
            @ScytheStick.canceled += instance.OnScytheStick;
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MovementActions" />
        private void UnregisterCallbacks(IMovementActions instance)
        {
            @Fireball.started -= instance.OnFireball;
            @Fireball.performed -= instance.OnFireball;
            @Fireball.canceled -= instance.OnFireball;
            @DropEgg.started -= instance.OnDropEgg;
            @DropEgg.performed -= instance.OnDropEgg;
            @DropEgg.canceled -= instance.OnDropEgg;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Drop.started -= instance.OnDrop;
            @Drop.performed -= instance.OnDrop;
            @Drop.canceled -= instance.OnDrop;
            @JumpRight.started -= instance.OnJumpRight;
            @JumpRight.performed -= instance.OnJumpRight;
            @JumpRight.canceled -= instance.OnJumpRight;
            @JumpLeft.started -= instance.OnJumpLeft;
            @JumpLeft.performed -= instance.OnJumpLeft;
            @JumpLeft.canceled -= instance.OnJumpLeft;
            @JumpHold.started -= instance.OnJumpHold;
            @JumpHold.performed -= instance.OnJumpHold;
            @JumpHold.canceled -= instance.OnJumpHold;
            @TouchPress.started -= instance.OnTouchPress;
            @TouchPress.performed -= instance.OnTouchPress;
            @TouchPress.canceled -= instance.OnTouchPress;
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
            @Parachute.started -= instance.OnParachute;
            @Parachute.performed -= instance.OnParachute;
            @Parachute.canceled -= instance.OnParachute;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @DashSlash.started -= instance.OnDashSlash;
            @DashSlash.performed -= instance.OnDashSlash;
            @DashSlash.canceled -= instance.OnDashSlash;
            @EggJoystick.started -= instance.OnEggJoystick;
            @EggJoystick.performed -= instance.OnEggJoystick;
            @EggJoystick.canceled -= instance.OnEggJoystick;
            @SwitchAmmoRight.started -= instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.performed -= instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.canceled -= instance.OnSwitchAmmoRight;
            @Parry.started -= instance.OnParry;
            @Parry.performed -= instance.OnParry;
            @Parry.canceled -= instance.OnParry;
            @Finger1.started -= instance.OnFinger1;
            @Finger1.performed -= instance.OnFinger1;
            @Finger1.canceled -= instance.OnFinger1;
            @Finger2.started -= instance.OnFinger2;
            @Finger2.performed -= instance.OnFinger2;
            @Finger2.canceled -= instance.OnFinger2;
            @Cursor.started -= instance.OnCursor;
            @Cursor.performed -= instance.OnCursor;
            @Cursor.canceled -= instance.OnCursor;
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
            @Finger1Press.started -= instance.OnFinger1Press;
            @Finger1Press.performed -= instance.OnFinger1Press;
            @Finger1Press.canceled -= instance.OnFinger1Press;
            @Finger2Press.started -= instance.OnFinger2Press;
            @Finger2Press.performed -= instance.OnFinger2Press;
            @Finger2Press.canceled -= instance.OnFinger2Press;
            @ScytheStick.started -= instance.OnScytheStick;
            @ScytheStick.performed -= instance.OnScytheStick;
            @ScytheStick.canceled -= instance.OnScytheStick;
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MovementActions.UnregisterCallbacks(IMovementActions)" />.
        /// </summary>
        /// <seealso cref="MovementActions.UnregisterCallbacks(IMovementActions)" />
        public void RemoveCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MovementActions.AddCallbacks(IMovementActions)" />
        /// <seealso cref="MovementActions.RemoveCallbacks(IMovementActions)" />
        /// <seealso cref="MovementActions.UnregisterCallbacks(IMovementActions)" />
        public void SetCallbacks(IMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MovementActions" /> instance referencing this action map.
    /// </summary>
    public MovementActions @Movement => new MovementActions(this);

    // LevelCreator
    private readonly InputActionMap m_LevelCreator;
    private List<ILevelCreatorActions> m_LevelCreatorActionsCallbackInterfaces = new List<ILevelCreatorActions>();
    private readonly InputAction m_LevelCreator_Finger1Press;
    private readonly InputAction m_LevelCreator_Finger1Pos;
    private readonly InputAction m_LevelCreator_CursorClick;
    private readonly InputAction m_LevelCreator_CursorPos;
    private readonly InputAction m_LevelCreator_Finger2Press;
    private readonly InputAction m_LevelCreator_Finger2Pos;
    private readonly InputAction m_LevelCreator_ShiftClick;
    /// <summary>
    /// Provides access to input actions defined in input action map "LevelCreator".
    /// </summary>
    public struct LevelCreatorActions
    {
        private @InputController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public LevelCreatorActions(@InputController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "LevelCreator/Finger1Press".
        /// </summary>
        public InputAction @Finger1Press => m_Wrapper.m_LevelCreator_Finger1Press;
        /// <summary>
        /// Provides access to the underlying input action "LevelCreator/Finger1Pos".
        /// </summary>
        public InputAction @Finger1Pos => m_Wrapper.m_LevelCreator_Finger1Pos;
        /// <summary>
        /// Provides access to the underlying input action "LevelCreator/CursorClick".
        /// </summary>
        public InputAction @CursorClick => m_Wrapper.m_LevelCreator_CursorClick;
        /// <summary>
        /// Provides access to the underlying input action "LevelCreator/CursorPos".
        /// </summary>
        public InputAction @CursorPos => m_Wrapper.m_LevelCreator_CursorPos;
        /// <summary>
        /// Provides access to the underlying input action "LevelCreator/Finger2Press".
        /// </summary>
        public InputAction @Finger2Press => m_Wrapper.m_LevelCreator_Finger2Press;
        /// <summary>
        /// Provides access to the underlying input action "LevelCreator/Finger2Pos".
        /// </summary>
        public InputAction @Finger2Pos => m_Wrapper.m_LevelCreator_Finger2Pos;
        /// <summary>
        /// Provides access to the underlying input action "LevelCreator/ShiftClick".
        /// </summary>
        public InputAction @ShiftClick => m_Wrapper.m_LevelCreator_ShiftClick;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_LevelCreator; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="LevelCreatorActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(LevelCreatorActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="LevelCreatorActions" />
        public void AddCallbacks(ILevelCreatorActions instance)
        {
            if (instance == null || m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Add(instance);
            @Finger1Press.started += instance.OnFinger1Press;
            @Finger1Press.performed += instance.OnFinger1Press;
            @Finger1Press.canceled += instance.OnFinger1Press;
            @Finger1Pos.started += instance.OnFinger1Pos;
            @Finger1Pos.performed += instance.OnFinger1Pos;
            @Finger1Pos.canceled += instance.OnFinger1Pos;
            @CursorClick.started += instance.OnCursorClick;
            @CursorClick.performed += instance.OnCursorClick;
            @CursorClick.canceled += instance.OnCursorClick;
            @CursorPos.started += instance.OnCursorPos;
            @CursorPos.performed += instance.OnCursorPos;
            @CursorPos.canceled += instance.OnCursorPos;
            @Finger2Press.started += instance.OnFinger2Press;
            @Finger2Press.performed += instance.OnFinger2Press;
            @Finger2Press.canceled += instance.OnFinger2Press;
            @Finger2Pos.started += instance.OnFinger2Pos;
            @Finger2Pos.performed += instance.OnFinger2Pos;
            @Finger2Pos.canceled += instance.OnFinger2Pos;
            @ShiftClick.started += instance.OnShiftClick;
            @ShiftClick.performed += instance.OnShiftClick;
            @ShiftClick.canceled += instance.OnShiftClick;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="LevelCreatorActions" />
        private void UnregisterCallbacks(ILevelCreatorActions instance)
        {
            @Finger1Press.started -= instance.OnFinger1Press;
            @Finger1Press.performed -= instance.OnFinger1Press;
            @Finger1Press.canceled -= instance.OnFinger1Press;
            @Finger1Pos.started -= instance.OnFinger1Pos;
            @Finger1Pos.performed -= instance.OnFinger1Pos;
            @Finger1Pos.canceled -= instance.OnFinger1Pos;
            @CursorClick.started -= instance.OnCursorClick;
            @CursorClick.performed -= instance.OnCursorClick;
            @CursorClick.canceled -= instance.OnCursorClick;
            @CursorPos.started -= instance.OnCursorPos;
            @CursorPos.performed -= instance.OnCursorPos;
            @CursorPos.canceled -= instance.OnCursorPos;
            @Finger2Press.started -= instance.OnFinger2Press;
            @Finger2Press.performed -= instance.OnFinger2Press;
            @Finger2Press.canceled -= instance.OnFinger2Press;
            @Finger2Pos.started -= instance.OnFinger2Pos;
            @Finger2Pos.performed -= instance.OnFinger2Pos;
            @Finger2Pos.canceled -= instance.OnFinger2Pos;
            @ShiftClick.started -= instance.OnShiftClick;
            @ShiftClick.performed -= instance.OnShiftClick;
            @ShiftClick.canceled -= instance.OnShiftClick;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="LevelCreatorActions.UnregisterCallbacks(ILevelCreatorActions)" />.
        /// </summary>
        /// <seealso cref="LevelCreatorActions.UnregisterCallbacks(ILevelCreatorActions)" />
        public void RemoveCallbacks(ILevelCreatorActions instance)
        {
            if (m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="LevelCreatorActions.AddCallbacks(ILevelCreatorActions)" />
        /// <seealso cref="LevelCreatorActions.RemoveCallbacks(ILevelCreatorActions)" />
        /// <seealso cref="LevelCreatorActions.UnregisterCallbacks(ILevelCreatorActions)" />
        public void SetCallbacks(ILevelCreatorActions instance)
        {
            foreach (var item in m_Wrapper.m_LevelCreatorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="LevelCreatorActions" /> instance referencing this action map.
    /// </summary>
    public LevelCreatorActions @LevelCreator => new LevelCreatorActions(this);

    // GamepadCursor
    private readonly InputActionMap m_GamepadCursor;
    private List<IGamepadCursorActions> m_GamepadCursorActionsCallbackInterfaces = new List<IGamepadCursorActions>();
    private readonly InputAction m_GamepadCursor_MoveCursor;
    private readonly InputAction m_GamepadCursor_Select;
    /// <summary>
    /// Provides access to input actions defined in input action map "GamepadCursor".
    /// </summary>
    public struct GamepadCursorActions
    {
        private @InputController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GamepadCursorActions(@InputController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GamepadCursor/MoveCursor".
        /// </summary>
        public InputAction @MoveCursor => m_Wrapper.m_GamepadCursor_MoveCursor;
        /// <summary>
        /// Provides access to the underlying input action "GamepadCursor/Select".
        /// </summary>
        public InputAction @Select => m_Wrapper.m_GamepadCursor_Select;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GamepadCursor; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GamepadCursorActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GamepadCursorActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GamepadCursorActions" />
        public void AddCallbacks(IGamepadCursorActions instance)
        {
            if (instance == null || m_Wrapper.m_GamepadCursorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamepadCursorActionsCallbackInterfaces.Add(instance);
            @MoveCursor.started += instance.OnMoveCursor;
            @MoveCursor.performed += instance.OnMoveCursor;
            @MoveCursor.canceled += instance.OnMoveCursor;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GamepadCursorActions" />
        private void UnregisterCallbacks(IGamepadCursorActions instance)
        {
            @MoveCursor.started -= instance.OnMoveCursor;
            @MoveCursor.performed -= instance.OnMoveCursor;
            @MoveCursor.canceled -= instance.OnMoveCursor;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GamepadCursorActions.UnregisterCallbacks(IGamepadCursorActions)" />.
        /// </summary>
        /// <seealso cref="GamepadCursorActions.UnregisterCallbacks(IGamepadCursorActions)" />
        public void RemoveCallbacks(IGamepadCursorActions instance)
        {
            if (m_Wrapper.m_GamepadCursorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GamepadCursorActions.AddCallbacks(IGamepadCursorActions)" />
        /// <seealso cref="GamepadCursorActions.RemoveCallbacks(IGamepadCursorActions)" />
        /// <seealso cref="GamepadCursorActions.UnregisterCallbacks(IGamepadCursorActions)" />
        public void SetCallbacks(IGamepadCursorActions instance)
        {
            foreach (var item in m_Wrapper.m_GamepadCursorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamepadCursorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GamepadCursorActions" /> instance referencing this action map.
    /// </summary>
    public GamepadCursorActions @GamepadCursor => new GamepadCursorActions(this);
    private int m_KeyboardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_MobileSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme MobileScheme
    {
        get
        {
            if (m_MobileSchemeIndex == -1) m_MobileSchemeIndex = asset.FindControlSchemeIndex("Mobile");
            return asset.controlSchemes[m_MobileSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Movement" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MovementActions.AddCallbacks(IMovementActions)" />
    /// <seealso cref="MovementActions.RemoveCallbacks(IMovementActions)" />
    public interface IMovementActions
    {
        /// <summary>
        /// Method invoked when associated input action "Fireball" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFireball(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DropEgg" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDropEgg(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dash" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDash(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Drop" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDrop(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchPress" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchPress(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Parachute" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnParachute(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DashSlash" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDashSlash(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EggJoystick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEggJoystick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchAmmoRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchAmmoRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Parry" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnParry(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Finger1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Finger2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Cursor" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCursor(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MouseClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Finger1Press" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger1Press(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Finger2Press" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger2Press(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScytheStick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScytheStick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Trigger" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrigger(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "LevelCreator" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="LevelCreatorActions.AddCallbacks(ILevelCreatorActions)" />
    /// <seealso cref="LevelCreatorActions.RemoveCallbacks(ILevelCreatorActions)" />
    public interface ILevelCreatorActions
    {
        /// <summary>
        /// Method invoked when associated input action "Finger1Press" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger1Press(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Finger1Pos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger1Pos(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CursorClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCursorClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CursorPos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCursorPos(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Finger2Press" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger2Press(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Finger2Pos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFinger2Pos(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ShiftClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShiftClick(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GamepadCursor" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GamepadCursorActions.AddCallbacks(IGamepadCursorActions)" />
    /// <seealso cref="GamepadCursorActions.RemoveCallbacks(IGamepadCursorActions)" />
    public interface IGamepadCursorActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveCursor" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveCursor(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Select" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelect(InputAction.CallbackContext context);
    }
}
