//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""af9450ba-218f-4f79-a3d6-827cbaa3990d"",
            ""actions"": [
                {
                    ""name"": ""Fireball"",
                    ""type"": ""Button"",
                    ""id"": ""65cbda46-3c59-45c5-84c0-f4670e81305b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropEgg"",
                    ""type"": ""Button"",
                    ""id"": ""c8406085-9a15-49ea-abe0-cfeaa5057678"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""9df870a7-2b9e-4307-b0ce-553eb6ecbcc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""03838bde-c4e5-4a85-b37a-f61f8f371e17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpRight"",
                    ""type"": ""Button"",
                    ""id"": ""711ca112-25f4-4f11-9efe-0c329e2f5064"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpLeft"",
                    ""type"": ""Button"",
                    ""id"": ""9b324f8c-5dcd-463d-927a-6b176a5951c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpHold"",
                    ""type"": ""Button"",
                    ""id"": ""7a1b2628-cdb6-44df-96c2-b30778de634d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPress"",
                    ""type"": ""Button"",
                    ""id"": ""c8666c9d-9f9a-44c8-bb01-83f974e4900a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""2f75b153-ec9f-4888-b592-e5c396cc1467"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Parachute"",
                    ""type"": ""Button"",
                    ""id"": ""267adbde-d536-4f69-acf1-6296c8214c71"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6a7bb245-7739-4352-a7ae-757bdda03107"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashSlash"",
                    ""type"": ""Button"",
                    ""id"": ""1cbbf4c4-de14-4525-b189-264d8197cd0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.32)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EggJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""35f59893-3e75-40e2-a4d0-0dee34bd09a0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchAmmoRight"",
                    ""type"": ""Button"",
                    ""id"": ""c40449bd-286c-47ed-a608-ea7c16437bc2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parry"",
                    ""type"": ""Button"",
                    ""id"": ""39317f21-516d-4ac9-9092-65462f989d96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finger1"",
                    ""type"": ""Value"",
                    ""id"": ""f3dba7fd-62b8-4eca-8fb3-d7282a84aded"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Finger2"",
                    ""type"": ""Value"",
                    ""id"": ""bdb83564-aa55-43f1-9528-78b208745e8a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cursor"",
                    ""type"": ""Value"",
                    ""id"": ""e16de448-4c6f-47e7-a3c8-eff0103230a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""b5a7659e-a41d-4218-b2c1-a8c67c25fb4c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finger1Press"",
                    ""type"": ""Button"",
                    ""id"": ""402a2127-185b-4a1f-941e-4c8d51739f64"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Finger2Press"",
                    ""type"": ""Button"",
                    ""id"": ""52ec2e1e-f0d9-4a07-954c-509764b986e5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScytheStick"",
                    ""type"": ""Value"",
                    ""id"": ""f467a2e1-3b7a-4f5e-82ec-910d70491803"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1509b281-cd61-4491-b3f1-45db31dbb1e8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""JumpHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""355bd070-138f-4545-96cf-bdcafae4e0e9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""JumpHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b7079e5-c39a-4c93-9bc7-410e1ac8487c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""JumpLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd76ad71-f0a6-4336-9bd4-73384afa7ea9"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""JumpLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c57ff5b-84f5-48d5-a121-b44e03cce482"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""JumpRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b08dbd0-a67f-40f2-bffa-22366bd91f60"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""JumpRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8f9e6a0-1c12-40f2-ab4c-42dfceff0d90"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6985edf9-1ce9-497d-a597-f45b7275fa2c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1118d868-368b-43b5-88e6-4caae8c07017"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9749ddd7-ac4f-4761-8675-9edfef8728e1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5ef087a-7730-41b6-b474-5933a45b45f7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DropEgg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b7f91a3-6adb-4672-8351-0d8d5e2a09f4"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""DropEgg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1d3526f-f1c8-41dd-9c85-ad65b57ce2bb"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Fireball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60037d80-6c76-40cd-b93a-47e30005c252"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Fireball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf6de740-0bd6-4f1d-abb7-6d15f43f259f"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70d7505d-0113-4039-8d8f-7839975a94fc"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d3349ca-646a-426f-a376-dbb4c1bd7a64"",
                    ""path"": ""<Keyboard>/#(C)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Parachute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02baf8d2-731d-48a2-9e7c-d6fdb850d492"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Parachute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71785b00-5b5a-4d60-a60a-bfe45c783bc6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47e0b5fe-6038-46bf-aba8-7552f7a46f65"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6624c8c8-2105-4363-885c-22ba6cf97fdf"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DashSlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7a56b1f-185b-4242-b3b9-7cee360a64d4"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""DashSlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f4be38a-3bd6-42be-b8dd-b1d9cd33a48c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""Mobile"",
                    ""action"": ""EggJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f47d7a75-c16b-4703-b2e2-e8a745cb011e"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SwitchAmmoRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf7b388c-28cc-4057-87aa-fadfcf6c81c8"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""038266cd-44a2-4c9b-b5cc-54d43586cd4d"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Finger1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b80bf30-2322-4d9e-9f05-7b81dfc016b8"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Finger2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff58ee2f-19e1-4384-8bbb-aca16047ab20"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8441d966-0d2f-4f44-a9e2-c0fa72351951"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdff57cc-ec27-401a-896c-02da72ebe67c"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Finger1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de286ed4-8cb4-49cf-8134-d6ccff632993"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Finger2Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eb466c8-22a1-4b84-a9d1-a0544dc66093"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScytheStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LevelCreator"",
            ""id"": ""89737611-948f-48ca-9565-39ddf240200a"",
            ""actions"": [
                {
                    ""name"": ""Finger1Press"",
                    ""type"": ""Button"",
                    ""id"": ""45e70696-90c1-48b5-9e35-5123eba41f05"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finger1Pos"",
                    ""type"": ""Value"",
                    ""id"": ""8f0d85d4-eca9-4570-acd9-098497705e1e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CursorClick"",
                    ""type"": ""Button"",
                    ""id"": ""d307f141-d5c9-40b2-84f1-4db248acddb1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorPos"",
                    ""type"": ""Value"",
                    ""id"": ""77f05261-ace6-490b-bf5b-dd444dc2cb1e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a7f57d9c-a9ab-413e-b4a9-b17c28c501cc"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b4f6e57-bff5-4d00-8090-ae98b2a41019"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mobile"",
                    ""action"": ""Finger1Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3607148-b743-4ea9-a632-7173f5db09d5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""CursorClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bee76cf7-05e0-4c1a-9504-af667fc8b6ed"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""CursorPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Mobile"",
            ""bindingGroup"": ""Mobile"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_Fireball = m_Movement.FindAction("Fireball", throwIfNotFound: true);
        m_Movement_DropEgg = m_Movement.FindAction("DropEgg", throwIfNotFound: true);
        m_Movement_Dash = m_Movement.FindAction("Dash", throwIfNotFound: true);
        m_Movement_Drop = m_Movement.FindAction("Drop", throwIfNotFound: true);
        m_Movement_JumpRight = m_Movement.FindAction("JumpRight", throwIfNotFound: true);
        m_Movement_JumpLeft = m_Movement.FindAction("JumpLeft", throwIfNotFound: true);
        m_Movement_JumpHold = m_Movement.FindAction("JumpHold", throwIfNotFound: true);
        m_Movement_TouchPress = m_Movement.FindAction("TouchPress", throwIfNotFound: true);
        m_Movement_TouchPosition = m_Movement.FindAction("TouchPosition", throwIfNotFound: true);
        m_Movement_Parachute = m_Movement.FindAction("Parachute", throwIfNotFound: true);
        m_Movement_Jump = m_Movement.FindAction("Jump", throwIfNotFound: true);
        m_Movement_DashSlash = m_Movement.FindAction("DashSlash", throwIfNotFound: true);
        m_Movement_EggJoystick = m_Movement.FindAction("EggJoystick", throwIfNotFound: true);
        m_Movement_SwitchAmmoRight = m_Movement.FindAction("SwitchAmmoRight", throwIfNotFound: true);
        m_Movement_Parry = m_Movement.FindAction("Parry", throwIfNotFound: true);
        m_Movement_Finger1 = m_Movement.FindAction("Finger1", throwIfNotFound: true);
        m_Movement_Finger2 = m_Movement.FindAction("Finger2", throwIfNotFound: true);
        m_Movement_Cursor = m_Movement.FindAction("Cursor", throwIfNotFound: true);
        m_Movement_MouseClick = m_Movement.FindAction("MouseClick", throwIfNotFound: true);
        m_Movement_Finger1Press = m_Movement.FindAction("Finger1Press", throwIfNotFound: true);
        m_Movement_Finger2Press = m_Movement.FindAction("Finger2Press", throwIfNotFound: true);
        m_Movement_ScytheStick = m_Movement.FindAction("ScytheStick", throwIfNotFound: true);
        // LevelCreator
        m_LevelCreator = asset.FindActionMap("LevelCreator", throwIfNotFound: true);
        m_LevelCreator_Finger1Press = m_LevelCreator.FindAction("Finger1Press", throwIfNotFound: true);
        m_LevelCreator_Finger1Pos = m_LevelCreator.FindAction("Finger1Pos", throwIfNotFound: true);
        m_LevelCreator_CursorClick = m_LevelCreator.FindAction("CursorClick", throwIfNotFound: true);
        m_LevelCreator_CursorPos = m_LevelCreator.FindAction("CursorPos", throwIfNotFound: true);
    }

    ~@InputController()
    {
        UnityEngine.Debug.Assert(!m_Movement.enabled, "This will cause a leak and performance issues, InputController.Movement.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_LevelCreator.enabled, "This will cause a leak and performance issues, InputController.LevelCreator.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private List<IMovementActions> m_MovementActionsCallbackInterfaces = new List<IMovementActions>();
    private readonly InputAction m_Movement_Fireball;
    private readonly InputAction m_Movement_DropEgg;
    private readonly InputAction m_Movement_Dash;
    private readonly InputAction m_Movement_Drop;
    private readonly InputAction m_Movement_JumpRight;
    private readonly InputAction m_Movement_JumpLeft;
    private readonly InputAction m_Movement_JumpHold;
    private readonly InputAction m_Movement_TouchPress;
    private readonly InputAction m_Movement_TouchPosition;
    private readonly InputAction m_Movement_Parachute;
    private readonly InputAction m_Movement_Jump;
    private readonly InputAction m_Movement_DashSlash;
    private readonly InputAction m_Movement_EggJoystick;
    private readonly InputAction m_Movement_SwitchAmmoRight;
    private readonly InputAction m_Movement_Parry;
    private readonly InputAction m_Movement_Finger1;
    private readonly InputAction m_Movement_Finger2;
    private readonly InputAction m_Movement_Cursor;
    private readonly InputAction m_Movement_MouseClick;
    private readonly InputAction m_Movement_Finger1Press;
    private readonly InputAction m_Movement_Finger2Press;
    private readonly InputAction m_Movement_ScytheStick;
    public struct MovementActions
    {
        private @InputController m_Wrapper;
        public MovementActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fireball => m_Wrapper.m_Movement_Fireball;
        public InputAction @DropEgg => m_Wrapper.m_Movement_DropEgg;
        public InputAction @Dash => m_Wrapper.m_Movement_Dash;
        public InputAction @Drop => m_Wrapper.m_Movement_Drop;
        public InputAction @JumpRight => m_Wrapper.m_Movement_JumpRight;
        public InputAction @JumpLeft => m_Wrapper.m_Movement_JumpLeft;
        public InputAction @JumpHold => m_Wrapper.m_Movement_JumpHold;
        public InputAction @TouchPress => m_Wrapper.m_Movement_TouchPress;
        public InputAction @TouchPosition => m_Wrapper.m_Movement_TouchPosition;
        public InputAction @Parachute => m_Wrapper.m_Movement_Parachute;
        public InputAction @Jump => m_Wrapper.m_Movement_Jump;
        public InputAction @DashSlash => m_Wrapper.m_Movement_DashSlash;
        public InputAction @EggJoystick => m_Wrapper.m_Movement_EggJoystick;
        public InputAction @SwitchAmmoRight => m_Wrapper.m_Movement_SwitchAmmoRight;
        public InputAction @Parry => m_Wrapper.m_Movement_Parry;
        public InputAction @Finger1 => m_Wrapper.m_Movement_Finger1;
        public InputAction @Finger2 => m_Wrapper.m_Movement_Finger2;
        public InputAction @Cursor => m_Wrapper.m_Movement_Cursor;
        public InputAction @MouseClick => m_Wrapper.m_Movement_MouseClick;
        public InputAction @Finger1Press => m_Wrapper.m_Movement_Finger1Press;
        public InputAction @Finger2Press => m_Wrapper.m_Movement_Finger2Press;
        public InputAction @ScytheStick => m_Wrapper.m_Movement_ScytheStick;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void AddCallbacks(IMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementActionsCallbackInterfaces.Add(instance);
            @Fireball.started += instance.OnFireball;
            @Fireball.performed += instance.OnFireball;
            @Fireball.canceled += instance.OnFireball;
            @DropEgg.started += instance.OnDropEgg;
            @DropEgg.performed += instance.OnDropEgg;
            @DropEgg.canceled += instance.OnDropEgg;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Drop.started += instance.OnDrop;
            @Drop.performed += instance.OnDrop;
            @Drop.canceled += instance.OnDrop;
            @JumpRight.started += instance.OnJumpRight;
            @JumpRight.performed += instance.OnJumpRight;
            @JumpRight.canceled += instance.OnJumpRight;
            @JumpLeft.started += instance.OnJumpLeft;
            @JumpLeft.performed += instance.OnJumpLeft;
            @JumpLeft.canceled += instance.OnJumpLeft;
            @JumpHold.started += instance.OnJumpHold;
            @JumpHold.performed += instance.OnJumpHold;
            @JumpHold.canceled += instance.OnJumpHold;
            @TouchPress.started += instance.OnTouchPress;
            @TouchPress.performed += instance.OnTouchPress;
            @TouchPress.canceled += instance.OnTouchPress;
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
            @Parachute.started += instance.OnParachute;
            @Parachute.performed += instance.OnParachute;
            @Parachute.canceled += instance.OnParachute;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @DashSlash.started += instance.OnDashSlash;
            @DashSlash.performed += instance.OnDashSlash;
            @DashSlash.canceled += instance.OnDashSlash;
            @EggJoystick.started += instance.OnEggJoystick;
            @EggJoystick.performed += instance.OnEggJoystick;
            @EggJoystick.canceled += instance.OnEggJoystick;
            @SwitchAmmoRight.started += instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.performed += instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.canceled += instance.OnSwitchAmmoRight;
            @Parry.started += instance.OnParry;
            @Parry.performed += instance.OnParry;
            @Parry.canceled += instance.OnParry;
            @Finger1.started += instance.OnFinger1;
            @Finger1.performed += instance.OnFinger1;
            @Finger1.canceled += instance.OnFinger1;
            @Finger2.started += instance.OnFinger2;
            @Finger2.performed += instance.OnFinger2;
            @Finger2.canceled += instance.OnFinger2;
            @Cursor.started += instance.OnCursor;
            @Cursor.performed += instance.OnCursor;
            @Cursor.canceled += instance.OnCursor;
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
            @Finger1Press.started += instance.OnFinger1Press;
            @Finger1Press.performed += instance.OnFinger1Press;
            @Finger1Press.canceled += instance.OnFinger1Press;
            @Finger2Press.started += instance.OnFinger2Press;
            @Finger2Press.performed += instance.OnFinger2Press;
            @Finger2Press.canceled += instance.OnFinger2Press;
            @ScytheStick.started += instance.OnScytheStick;
            @ScytheStick.performed += instance.OnScytheStick;
            @ScytheStick.canceled += instance.OnScytheStick;
        }

        private void UnregisterCallbacks(IMovementActions instance)
        {
            @Fireball.started -= instance.OnFireball;
            @Fireball.performed -= instance.OnFireball;
            @Fireball.canceled -= instance.OnFireball;
            @DropEgg.started -= instance.OnDropEgg;
            @DropEgg.performed -= instance.OnDropEgg;
            @DropEgg.canceled -= instance.OnDropEgg;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Drop.started -= instance.OnDrop;
            @Drop.performed -= instance.OnDrop;
            @Drop.canceled -= instance.OnDrop;
            @JumpRight.started -= instance.OnJumpRight;
            @JumpRight.performed -= instance.OnJumpRight;
            @JumpRight.canceled -= instance.OnJumpRight;
            @JumpLeft.started -= instance.OnJumpLeft;
            @JumpLeft.performed -= instance.OnJumpLeft;
            @JumpLeft.canceled -= instance.OnJumpLeft;
            @JumpHold.started -= instance.OnJumpHold;
            @JumpHold.performed -= instance.OnJumpHold;
            @JumpHold.canceled -= instance.OnJumpHold;
            @TouchPress.started -= instance.OnTouchPress;
            @TouchPress.performed -= instance.OnTouchPress;
            @TouchPress.canceled -= instance.OnTouchPress;
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
            @Parachute.started -= instance.OnParachute;
            @Parachute.performed -= instance.OnParachute;
            @Parachute.canceled -= instance.OnParachute;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @DashSlash.started -= instance.OnDashSlash;
            @DashSlash.performed -= instance.OnDashSlash;
            @DashSlash.canceled -= instance.OnDashSlash;
            @EggJoystick.started -= instance.OnEggJoystick;
            @EggJoystick.performed -= instance.OnEggJoystick;
            @EggJoystick.canceled -= instance.OnEggJoystick;
            @SwitchAmmoRight.started -= instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.performed -= instance.OnSwitchAmmoRight;
            @SwitchAmmoRight.canceled -= instance.OnSwitchAmmoRight;
            @Parry.started -= instance.OnParry;
            @Parry.performed -= instance.OnParry;
            @Parry.canceled -= instance.OnParry;
            @Finger1.started -= instance.OnFinger1;
            @Finger1.performed -= instance.OnFinger1;
            @Finger1.canceled -= instance.OnFinger1;
            @Finger2.started -= instance.OnFinger2;
            @Finger2.performed -= instance.OnFinger2;
            @Finger2.canceled -= instance.OnFinger2;
            @Cursor.started -= instance.OnCursor;
            @Cursor.performed -= instance.OnCursor;
            @Cursor.canceled -= instance.OnCursor;
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
            @Finger1Press.started -= instance.OnFinger1Press;
            @Finger1Press.performed -= instance.OnFinger1Press;
            @Finger1Press.canceled -= instance.OnFinger1Press;
            @Finger2Press.started -= instance.OnFinger2Press;
            @Finger2Press.performed -= instance.OnFinger2Press;
            @Finger2Press.canceled -= instance.OnFinger2Press;
            @ScytheStick.started -= instance.OnScytheStick;
            @ScytheStick.performed -= instance.OnScytheStick;
            @ScytheStick.canceled -= instance.OnScytheStick;
        }

        public void RemoveCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovementActions @Movement => new MovementActions(this);

    // LevelCreator
    private readonly InputActionMap m_LevelCreator;
    private List<ILevelCreatorActions> m_LevelCreatorActionsCallbackInterfaces = new List<ILevelCreatorActions>();
    private readonly InputAction m_LevelCreator_Finger1Press;
    private readonly InputAction m_LevelCreator_Finger1Pos;
    private readonly InputAction m_LevelCreator_CursorClick;
    private readonly InputAction m_LevelCreator_CursorPos;
    public struct LevelCreatorActions
    {
        private @InputController m_Wrapper;
        public LevelCreatorActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Finger1Press => m_Wrapper.m_LevelCreator_Finger1Press;
        public InputAction @Finger1Pos => m_Wrapper.m_LevelCreator_Finger1Pos;
        public InputAction @CursorClick => m_Wrapper.m_LevelCreator_CursorClick;
        public InputAction @CursorPos => m_Wrapper.m_LevelCreator_CursorPos;
        public InputActionMap Get() { return m_Wrapper.m_LevelCreator; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LevelCreatorActions set) { return set.Get(); }
        public void AddCallbacks(ILevelCreatorActions instance)
        {
            if (instance == null || m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Add(instance);
            @Finger1Press.started += instance.OnFinger1Press;
            @Finger1Press.performed += instance.OnFinger1Press;
            @Finger1Press.canceled += instance.OnFinger1Press;
            @Finger1Pos.started += instance.OnFinger1Pos;
            @Finger1Pos.performed += instance.OnFinger1Pos;
            @Finger1Pos.canceled += instance.OnFinger1Pos;
            @CursorClick.started += instance.OnCursorClick;
            @CursorClick.performed += instance.OnCursorClick;
            @CursorClick.canceled += instance.OnCursorClick;
            @CursorPos.started += instance.OnCursorPos;
            @CursorPos.performed += instance.OnCursorPos;
            @CursorPos.canceled += instance.OnCursorPos;
        }

        private void UnregisterCallbacks(ILevelCreatorActions instance)
        {
            @Finger1Press.started -= instance.OnFinger1Press;
            @Finger1Press.performed -= instance.OnFinger1Press;
            @Finger1Press.canceled -= instance.OnFinger1Press;
            @Finger1Pos.started -= instance.OnFinger1Pos;
            @Finger1Pos.performed -= instance.OnFinger1Pos;
            @Finger1Pos.canceled -= instance.OnFinger1Pos;
            @CursorClick.started -= instance.OnCursorClick;
            @CursorClick.performed -= instance.OnCursorClick;
            @CursorClick.canceled -= instance.OnCursorClick;
            @CursorPos.started -= instance.OnCursorPos;
            @CursorPos.performed -= instance.OnCursorPos;
            @CursorPos.canceled -= instance.OnCursorPos;
        }

        public void RemoveCallbacks(ILevelCreatorActions instance)
        {
            if (m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILevelCreatorActions instance)
        {
            foreach (var item in m_Wrapper.m_LevelCreatorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LevelCreatorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LevelCreatorActions @LevelCreator => new LevelCreatorActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_MobileSchemeIndex = -1;
    public InputControlScheme MobileScheme
    {
        get
        {
            if (m_MobileSchemeIndex == -1) m_MobileSchemeIndex = asset.FindControlSchemeIndex("Mobile");
            return asset.controlSchemes[m_MobileSchemeIndex];
        }
    }
    public interface IMovementActions
    {
        void OnFireball(InputAction.CallbackContext context);
        void OnDropEgg(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
        void OnJumpRight(InputAction.CallbackContext context);
        void OnJumpLeft(InputAction.CallbackContext context);
        void OnJumpHold(InputAction.CallbackContext context);
        void OnTouchPress(InputAction.CallbackContext context);
        void OnTouchPosition(InputAction.CallbackContext context);
        void OnParachute(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDashSlash(InputAction.CallbackContext context);
        void OnEggJoystick(InputAction.CallbackContext context);
        void OnSwitchAmmoRight(InputAction.CallbackContext context);
        void OnParry(InputAction.CallbackContext context);
        void OnFinger1(InputAction.CallbackContext context);
        void OnFinger2(InputAction.CallbackContext context);
        void OnCursor(InputAction.CallbackContext context);
        void OnMouseClick(InputAction.CallbackContext context);
        void OnFinger1Press(InputAction.CallbackContext context);
        void OnFinger2Press(InputAction.CallbackContext context);
        void OnScytheStick(InputAction.CallbackContext context);
    }
    public interface ILevelCreatorActions
    {
        void OnFinger1Press(InputAction.CallbackContext context);
        void OnFinger1Pos(InputAction.CallbackContext context);
        void OnCursorClick(InputAction.CallbackContext context);
        void OnCursorPos(InputAction.CallbackContext context);
    }
}
